# Generated by Django 2.2.6 on 2020-02-09 04:17

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200202_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
