# Generated by Django 2.2.6 on 2020-02-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200209_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cate1',
        ),
        migrations.AddField(
            model_name='category',
            name='cate2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
