# Generated by Django 2.2.6 on 2020-02-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200209_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cate1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cate2',
        ),
    ]
