# Generated by Django 2.2.6 on 2020-02-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200212_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
